//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSHDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Heroinas
    {
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Alias { get; set; }
        public Nullable<int> ID_CreadoX { get; set; }
        public Nullable<int> ID_Origen { get; set; }
    
        public virtual CreadoX CreadoX { get; set; }
        public virtual Origenes Origenes { get; set; }
    }
}
